### ISSUE TITLE
Upgrade to Argo 2.12.0

### ISSUE THREAD

**Issue by tumido** [AICoE/idh-manifests#56]
Once Argo 2.12.0 is finally out (with RBAC and stuff), work together with Thoth to get the images updated (maybe move the quay repos from thoth-station to aicoe?) and update the deployment state from the current inconsistent state where 2.11.1 manifests are used with 2.11.0 images.

Reference: #55

/assign @tumido

**Comment by anishasthana** [comment]
@tumido this was closed by #62  right?

**Comment by tumido** [comment]
yes, thank you :slightly_smiling_face:
