### ISSUE TITLE
Have an image that has enhanced cookiecutter template with reusable functionalities

### ISSUE THREAD

**Issue by pacospace** [AICoE/idh-manifests#9]
As Data Scientist/acting Software Engineer,

I would like to have an image that is based on common structure regarding Data Science project (e.g cookicutter) and some utils/functionalities that can be reusable (e.g. reading/storing file on Ceph, connect to Spark), either source code or template notebooks. 

Having one git repository build with those requirements can be built automatically with the CI and we could all contribute to have not only a structure but common functionalities in order to avoid reinventing the wheel.

References:
- https://drivendata.github.io/cookiecutter-data-science/
- https://github.com/aicoe-aiops/project-template

**Comment by anishasthana** [comment]
Is this something we could have built with the aicoe-ci pipelines? @harshad16

**Comment by anishasthana** [comment]
@MichaelClifford Please weigh in here as well with any things the image should have.

**Comment by pacospace** [comment]
> Is this something we could have built with the aicoe-ci pipelines? @harshad16

We could create a repo `enhanced-cookicutter-notebook` which has

- the basic repo structure
- template notebook
- functionalities in `/src` used in those template notebook

Template notebooks:
- `create-dataset` with retrieve/store data from Ceph.

Maybe on top of that basic repo (`enhanced-cookicutter-notebook`) we can have `nlp-notebook` (basic-repo + libraries NLP + notebooks for NLP.

Maybe we can have AICoE ML Application Zoo with images depending on the application that have template notebooks, Argo workflows templates, all to show application run on ODH.

**Comment by MichaelClifford** [comment]
I'm not sure if creating an `enhanced-cookiecutter` is the way to go. Shouldn't we maintain `aicoe-aiops/project-template` as the single source, make updates there that can be used by everyone as either a new repo template or as a JH image.  

I think the changes you're suggesting @pacospace are good, but they should be made to the existing template, right?

**Comment by pacospace** [comment]
> I'm not sure if creating an `enhanced-cookiecutter` is the way to go. Shouldn't we maintain `aicoe-aiops/project-template` as the single source, make updates there that can be used by everyone as either a new repo template or as a JH image.
> 
> I think the changes you're suggesting @pacospace are good, but they should be made to the existing template, right?

Yes definitely, the base would be `aicoe-aiops/project-template` :)
